##### Begin Parameters #####
Parameters:

  #Dropbox example, using predefiend values
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
    #Constraint Description will be displayed, incase of error
    ConstraintDescription: Choose, t1.micro, t2.nana, t2.micro from the list. Default is t2.micro

  #Dropbox example, retrieve KeyPair from your AWS account
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::Name
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  
  #String input examples
  InstanceName:
    Description: ShaiM-EC2-26
    Type: String
    
##### End Parameters #####

##### Begin Resources #####
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      #we reference the InstanceType parameter
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0a1a70369f0fce06a
      Tags:
      - Key: Name
        Value: !Ref InstanceName
      SubnetId: !Ref MySubnet1

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - CidrIp: !Ref SecurityGroupIngressCIDR
          FromPort: !Ref SecurityGroupPort
          ToPort: !Ref SecurityGroupPort
          IpProtocol: tcp
      VpcId: !Ref MyVPC

  MySubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      # the select function allows us to select across a list
      CidrBlock: !Select [0, !Ref MySubnetIpBlocks]

  MySubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      # the select function allows us to select across a list
      CidrBlock: !Select [1, !Ref MySubnetIpBlocks]
      
  MySubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      # the select function allows us to select across a list
      CidrBlock: !Select [2, !Ref MySubnetIpBlocks]
##### End Resources #####
