##### Begin Parameters #####
Parameters:

  #Dropbox example, using predefiend values
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
    #Constraint Description will be displayed, incase of error
    ConstraintDescription: Choose, t1.micro, t2.nana, t2.micro from the list. Default is t2.micro

  #Dropbox example, retrieve KeyPair from your AWS account
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  
  #String input examples
  InstanceName:
    Description: ShaiM-EC2-Lab10
    Type: String
##### End Parameters #####
